# Need to install hyprpaper, and enable wallpaper daemon:
# systemctl --user enable --now hyprpaper.service
wallpaper {
    monitor = eDP-1
    path = /home/skeet/Pictures/Dank Papes/Stupid, But Dank/Cats and Flowers.jpg
    fit_mode = cover
}

splash = false
