#!/usr/bin/env bash
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# This hook includes three examples. The first one removes the
# "# Please enter the commit message..." help message.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Regexp that extracts a Jira ID from the committing branch name
# We expect this to be some uppercase project key followed by some number
TICKETHOOK_JIRA_ID="${TICKETHOOK_JIRA_ID:=$(git rev-parse --abbrev-ref HEAD | grep -oE '[[:upper:]]{2,255}-[[:digit:]]+')}"
TICKETHOOK_FAIL_IF_DNE="${TICKETHOOK_FAIL_IF_DNE:=meow}"

COMMIT_MSG_FILE_CONTENTS=$(cat $COMMIT_MSG_FILE)

if [[ -z $TICKETHOOK_JIRA_ID ]]; then
  if [[ "$TICKETHOOK_FAIL_IF_DNE" = "true" ]]; then
    echo "{TICKETHOOK} FATAL: Failed to identify Jira ID in branch name"
    exit 1
  else
    echo "{TICKETHOOK} WARNING: Failed to identify Jira ID in branch name"
  fi

# If Jira ID is already at the beginning of the commit message, don't prepend it
elif [[ -n $(head -n1 $COMMIT_MSG_FILE | grep -oE "^$TICKETHOOK_JIRA_ID: ") ]]; then
  echo "{TICKETHOOK} WARNING: Found current Jira ID, $TICKETHOOK_JIRA_ID, at beginning of commit message. Did not prepend"
  exit 0

else
  echo "Jira ID extracted from branch name: $TICKETHOOK_JIRA_ID"
  { echo -n "$TICKETHOOK_JIRA_ID: "; echo -n "$COMMIT_MSG_FILE_CONTENTS"; } > $COMMIT_MSG_FILE
fi
